// resources/js/vuejs/components/Welcome.vue
<template>
  <div class="container">
    <div class="card">
      <div class="card-content">
        <span
          class="card-title orange-text center"
        >A Simple Frontend framework Scaffolding for CodeIgniter</span>
        <p class="green-text darken-2 center">Welcome to CodeIgniter_vue_materialize-css 3.1.10</p>
        <p class="teal-text darken-2 center">Created by Jinesh Francis</p>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  mounted() {
    console.log("Component mounted.");
  }
};
</script>

// resources/js/react/src/components/Welcome.js
import React, { Component } from 'react';

class Welcome extends Component {
	render() {
		const { name, content } = this.props;
		return (
			/**
			 * Bootstrap
			 */
			<div className="container">
				<div className="card text-center">
					<div className="card-block ">
						<h2 className="card-title text-success ">{name}</h2>
						<h5 className="card-text text-danger ">{content}</h5>
					</div>
				</div>
			</div>

			/**
			 * Materialize-css
			 */
			// <div className="container">
			// 	<div className="card">
			// 		<div className="card-content">
			// 			<span className="card-title orange-text center">{name}</span>
			// 			<p className="green-text darken-2 center">{content}</p>
			// 		</div>
			// 	</div>
			// </div>
		);
	}
}

export default Welcome;
